version: '3.9'
services:
  parsedmarc:
    build:
      context: docker-config/parsedmarc
    volumes:
      - ./files:/input:ro
      - ./output_files:/output
    command: parsedmarc -c /parsedmarc.ini /input/* --debug
    depends_on:
      - elasticsearch
    restart: on-failure

  elasticsearch:
    build:
      context: docker-config/elasticsearch
    environment:
      - discovery.type=single-node
    volumes:
      - elastic_data:/usr/share/elasticsearch/data

  grafana:
    build:
      context: docker-config/grafana
    ports:
      - ${DOCKER_GRAFANA_EXPOSED_PORT:-3000}:3000
    user: root
    environment:
      GF_INSTALL_PLUGINS: grafana-piechart-panel,grafana-worldmap-panel
      GF_AUTH_ANONYMOUS_ENABLED: 'true'

volumes:
  elastic_data: